
'use server'

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'

export async function createRoom(prevState: any, formData: FormData) {
    const supabase = await createClient()

    // 1. Check Authentication
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return { message: '로그인이 필요합니다.' }
    }

    // 2. Validate Input
    const name = formData.get('name') as string
    const description = formData.get('description') as string
    const startDate = formData.get('startDate') as string
    const endDate = formData.get('endDate') as string
    const communicationLink = formData.get('communicationLink') as string
    const isPublic = formData.get('isPublic') === 'on'

    if (!name || !startDate || !endDate) {
        return { message: '필수 항목을 모두 입력해주세요.' }
    }

    // 3. Insert Room
    const { data: room, error: roomError } = await supabase
        .from('rooms')
        .insert({
            name,
            description,
            start_date: startDate,
            end_date: endDate,
            communication_link: communicationLink,
            is_public: isPublic,
            owner_id: user.id,
            // invite_code will be generated by DB or we can generate it here if needed. 
            // For now, let's assume we might need a trigger or generate it here.
            // Let's generate a simple random code here for now.
            invite_code: Math.random().toString(36).substring(2, 8).toUpperCase()
        })
        .select()
        .single()

    if (roomError) {
        console.error('Room Creation Error:', roomError)
        return { message: '스터디 생성 중 오류가 발생했습니다.' }
    }

    // 4. Add Creator as OWNER in participants
    const { error: participantError } = await supabase
        .from('room_participants')
        .insert({
            room_id: room.id,
            user_id: user.id,
            role: 'OWNER',
            vacation_count: 1 // Default
        })

    if (participantError) {
        console.error('Participant Error:', participantError)
        return { message: '참여자 등록 중 오류가 발생했습니다.' }
    }

    // 5. Redirect to Room
    redirect(`/room/${room.id}`)
}

export async function joinRoom(roomId: string) {
    const supabase = await createClient()

    // 1. Check Auth
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return { message: '로그인이 필요합니다.' }
    }

    // 2. Check if already a member
    const { data: existingMember } = await supabase
        .from('room_participants')
        .select('role')
        .eq('room_id', roomId)
        .eq('user_id', user.id)
        .single()

    if (existingMember) {
        return { message: '이미 참여 중인 스터디입니다.' }
    }

    // 3. Insert Participant
    const { error } = await supabase
        .from('room_participants')
        .insert({
            room_id: roomId,
            user_id: user.id,
            role: 'MEMBER',
            vacation_count: 1
        })

    if (error) {
        console.error('Join Room Error:', error)
        return { message: '스터디 참여 중 오류가 발생했습니다.' }
    }

    // 4. Revalidate
    revalidatePath(`/room/${roomId}`)
    return { success: true }
}
